

INSERT INTO ORG_COMPANY(ID,NAME,STATUS,TENANT_ID) VALUES(1,'北京盛安德科技发展有限公司',1,'1');


INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,TENANT_ID) VALUES(1,'市场部',1,'1');
INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,TENANT_ID) VALUES(2,'财务部',1,'1');
INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,TENANT_ID) VALUES(3,'人事部',1,'1');
INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,TENANT_ID) VALUES(4,'研发部',1,'1');

